SELECT * FROM EMPLOYEES;

SELECT * FROM DEPARTMENTS;
--SQL is not case sensitive

select * from LOCATIONS;

select COUNTRY_NAME, REGION_ID from COUNTRIES;

SELECT JOB_ID, JOB_TITLE from JOBS;

SELECT * from EMPLOYEES
ORDER BY FIRST_NAME ASC, LAST_NAME DESC;