SELECT * from Employees
         where FIRST_NAME= 'David' AND LAST_Name='Lee';

SELECT FIRST_NAME, LAST_NAME, SALARY
from EMPLOYEES
where FIRST_NAME='Peter';

SELECT * FROM EMPLOYEES
WHERE SALARY>6000;

SELECT EMAIL FROM EMPLOYEES
WHERE SALARY>6000;

SELECT * FROM EMPLOYEES
WHERE SALARY>7000 AND DEPARTMENT_ID=60;

SELECT * FROM EMPLOYEES
WHERE SALARY>=3000 AND SALARY<=7000;

SELECT * FROM  EMPLOYEES
WHERE JOB_ID = 'IT_PROG' OR JOB_ID='MK_MAN';

SELECT * FROM COUNTRIES
WHERE COUNTRY_ID IN ('US', 'IT');

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID IS NULL;

SELECT * FROM EMPLOYEES
ORDER BY SALARY ASC;

SELECT * FROM EMPLOYEES
WHERE EMPLOYEE_ID < 120
ORDER BY SALARY ASC;